additionalLabels:
  app: mongodb
architecture: replicaset
replicaCount: 3
rbac:
  create: true
persistence:
  storageClass: nfs-client
  accessModes:
  - ReadWriteMany
auth:
  rootUser: root
  rootPassword: mongodb1234
automountServiceAccountToken: true
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        topologyKey: "kubernetes.io/hostname"
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - mongodb