apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: dev
  labels:
    app: viettin-be
spec:
  replicas: 10
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: viettin-be
  template:
    metadata:
      labels:
        app: viettin-be
    spec:
      containers:
        - name: viettin-be
          image: dongnguyen64/viettin-be-rabbitmq:latest
          env:
            - name: ENV
              value: "dev"
          ports:
            - containerPort: 5022
          volumeMounts:
            - name: config-env
              mountPath: /viettin-backend/config/
      volumes:
        - name: config-env
          configMap:
            name: my-configmap
      imagePullSecrets:
        - name: regcred
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - viettin-be
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: dev
  labels:
    app: viettin-be-service
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5022
    targetPort: 5022
  selector:
    app: viettin-be